DROP DATABASE IF EXISTS security1;
CREATE DATABASE security1;
USE security1;

CREATE TABLE `user`(
 id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
 username VARCHAR(20) NOT NULL,
 `password` VARCHAR(60) NOT NULL,
 email VARCHAR(40) NOT NULL,
 `role` VARCHAR(20) NOT NULL,
 create_date DATETIME NOT NULL
);

SELECT * FROM `user`;